### PR TITLE
Add files and documentation for cloudkey support.

### PR DESCRIPTION
**Pull request by potto007**
I got this working as a service on my Unifi CloudKey. I thought I'd share this with you in case you wanted to include it with your project. I isolated the cloudkey related stuff to a new subdirectory, so it doesn't muddy up the project.

I did my best to create a clear README file for the procedure. I considered a script, but thought people would probably prefer to see what's going on when it comes to their networking gear. 😄

### CODE REVIEW

**Comment by tdack** [comment]
The CloudKey has node & npm installed? Or are there extra steps required to install them on the CloudKey?

**Comment by potto007** [comment]
Yep, I could hardly believe it when I first saw it. The CloudKey runs: several JVMs, MongoDB (?!), node, php, nginx, and who knows what else.

**Comment by potto007** [comment]
@Duttch Thanks for posting that question. I went back through the steps in my README one by one, and realized that I didn't make one very important update to them. Step 5 should NOT make a symbolic link for the service, because systemd fails to start the service as a result of too many levels of symlinks. I'll submit a patch to fix that one line, but to get you up and running, do the following:
1. `unlink /lib/systemd/system/unifi-parental.service`
2. `ln /usr/local/src/unifi-parental/cloudkey/unifi-parental.service /lib/systemd/system/`
3. `systemctl daemon-reload` (just to be sure)
4. `systemctl enable unifi-parental`
5. `systemctl start unifi-parental`
Within 20 seconds you should be able to access the unifi-parental webapp.

Let me know if that gets you up and running!

Paul

**Comment by potto007** [comment]
Fixed this with https://github.com/tdack/unifi-parental/pull/7

**Comment by Duttch** [comment]
Hi Paul,

Removed the install and redid following the new steps etc.  I'm still getting a 502 Bad Gateway.

Maurice

**Comment by potto007** [comment]
Hi Maurice,

Thanks for trying that and giving feedback on the results. I appreciate you trying this out, as this wouldn't be a good contribution if it only works for me. :)

When you get a chance, can you please paste the results of the following?

```
systemctl status unifi-parental
ps aux | grep unifi-parental
ps aux | grep node
netstat -plnt | grep ':4000'
```

Also, I am using the most recent stable versions of the Controller (5.8.24-11016) and the CloudKey (0.11.4), fwiw.

**Comment by Duttch** [comment]
Hi Paul,

Just before you replied I did notice that the service is not active due to the start limit.  I've rebooted the cloudkey, but haven't been able to reset the systemd.

Maurice



Last login: Mon Jul 16 10:38:36 2018
root@UniFi-CloudKey:~# systemctl status unifi-parental
* unifi-parental.service - unifi-parental
   Loaded: loaded (/lib/systemd/system/unifi-parental.service; enabled)
   Active: failed (Result: start-limit) since Mon 2018-07-16 10:39:26 EDT; 5min ago
  Process: 849 ExecStart=/usr/local/src/unifi-parental/cloudkey/unifi-parental.sh (code=exited, status=203/EXEC)
 Main PID: 849 (code=exited, status=203/EXEC)
root@UniFi-CloudKey:~# ps aux | grep unifi-parental
root       910  0.0  0.0   2072   544 pts/0    S+   10:45   0:00 grep unifi-parental
root@UniFi-CloudKey:~# ps aux | grep node
root       377  2.6  1.3 142276 27704 ?        Ssl  10:38   0:10 /usr/bin/node /usr/share/bt-proxy/bt-proxy.js
root       912  0.0  0.0   2076   544 pts/0    S+   10:45   0:00 grep node
root@UniFi-CloudKey:~# netstat -plnt | grep ':4000'
tcp        0      0 10.0.0.2:4000           0.0.0.0:*               LISTEN      399/nginx -g daemon
root@UniFi-CloudKey:~#

**Comment by potto007** [comment]
So it's failing repeatedly. Is it creating a log file at `/usr/local/src/unifi-parental/cloudkey/unifi-parental.log`? If so, is there anything in there giving you indication of a problem? Also, can you make sure that `/usr/local/src/unifi-parental/cloudkey/unifi-parental.sh` kept its execute bit from my commit?

**Comment by Duttch** [comment]
Hi Paul,

It was the execute bit.  I see groups (2 - both undefined), but no mac addresses.

Thanks

Maurice

**Comment by potto007** [comment]
@Duttch - I'm guessing that you may not have your host value set in the controller block of config.json, or your .env is not configured with your `controller_user` and `controller_password`?

If you create a new Group, you should be seeing the Clients group populating with all Unifi's "Known Clients" in the listbox. Mine is a mixture of Mac addresses and custom names for those clients I've updated manually in the Unifi Controller  previously.

For comparison, this is what my config.json looks like:
```
{
  "controller": {
    "host": "192.168.1.10",
    "port": 8443,
    "user": "",
    "password": "",
    "site": "default"
  },
  "server": {
    "key": "cloudkey.key",
    "cert": "cloudkey.crt",
    "host": "127.0.0.1",
    "port": 4000
  },
```

**Comment by Duttch** [comment]
@potto007 - I dont have the site as default, but a secondary site.  Could that be the issue?

I have the .env configured

and my config.json is about the same, however when you add a group, the new data structure is different from the existing.

**Comment by potto007** [comment]
@Duttch - Reading what you said here, "...however when you add a group, the new data structure is different from the existing," led me to think that you may have started with the `config.json-sample`mentioned in the main project README. Looking at that file, it wasn't updated to reflect @tdack's refactor adding Groups. I would recommend starting with the `config.json` with the `data` section cleansed... so start with your config.json looking like this:

```
{
  "controller": {
    "host": "192.168.1.10",
    "port": 8443,
    "user": "",
    "password": "",
    "site": "default"
  },
  "server": {
    "key": "cloudkey.key",
    "cert": "cloudkey.crt",
    "host": "127.0.0.1",
    "port": 4000
  },
  "data": {}
}
```

**Comment by Duttch** [comment]
@potto007 - I did do a cleanup, and that took care of the unknown groups.  But the MAC/Clients are still not showing up,  I do wonder if its the site name.  The config.json uses "site" in the controller, but looking at the code in node-unifi, sites are referred to as "sites".

**Comment by Duttch** [comment]
@potto007 - Solved the issue.  It is the site name.  However the config.json var "site" should contain the unifi internal referral ID, not the site name.  In case of the default, it is "default", otherwise it can be found in: /srv/unifi/data/sites

Thanks

**Comment by Duttch** [comment]
@potto007 - The front end looks to work, however when I select a MAC addr and select access times and SAVE, the PC that is supposed to be blocked still has access to the internet.  Is it nessecary to do a forced provisioning ? or something else to apply the changes

I do have a USG 4 Pro, with cloudkey (all latest versions)

**Comment by tdack** [comment]
@Duttch it's not smart enough (yet) to see if there are clients that should be blocked immediately when you hit save. Also you can check the event log in the Unifi Controller to see if the nodejs application logged in and blocked/unblocked any clients.

**Comment by potto007** [comment]
Hi @Duttch - That's on the project's todo list on the project README: https://github.com/tdack/unifi-parental#todo. In its current form, the project is trigger-based only, as opposed to evaluating the state of a resource vs. the expected state. @tdack has a WIP refactor which appears to address this and other issues. I'm definitely interested in extending this, if he doesn't have time at the moment.

**Comment by potto007** [comment]
Incidentally, I have contributed to https://github.com/capitalone/cloud-custodian 's OffHours filter, which takes the same approach. It follows the "cronjob" approach, which seems to be a pretty common approach... Unfortunately, it becomes a pretty significant undertaking by the time people realize they want to handle "in-progress" states.

**Comment by Duttch** [comment]
@potto007 / @tdack - I've been diving a little deeper into the code and application of the parental controls.  I might have an idea around real-time application of the rules.

One could create a provisioning rule set based on the config.json of the current unifi-parental:

[https://community.ubnt.com/t5/EdgeRouter/Firewall-source-Mac-address-fails-on-commit/m-p/1773367#M141017](https://community.ubnt.com/t5/EdgeRouter/Firewall-source-Mac-address-fails-on-commit/m-p/1773367#M141017) - See time based blocking for EdgeRouter.

unifi-parental configures the config.json with the current input screen, then use the data in the config.json to create/update a config.gateway.json file [https://help.ubnt.com/hc/en-us/articles/215458888-UniFi-USG-Advanced-Configuration](https://help.ubnt.com/hc/en-us/articles/215458888-UniFi-USG-Advanced-Configuration) and send a Forced Provision to the USG.

**Comment by potto007** [comment]
@Duttch - that's a great find! I read about advanced firewall rules a couple months ago but was specifically looking at it for blacklisting, hadn't thought about the possibility of using it for parental lockouts. The fact that times are allowed in the rules is awesome. This form of blocking would likely replicate the experience I was accustomed to with the Google Wifi system - which is nice, because the devices stay connected, they just cannot do anything with the Internet; Chromebooks see this and give UI feedback that they are currently disabled.

This would obviously significantly change the approach of unifi-parental, so completely up to @tdack whether he's okay with it... that said, I think it would be great as a configurable option: ex. "blocking_type": "wifi" or "firewall"

**Comment by tdack** [comment]
I did look at pushing a config.json file but was trying to find a solution that didn't need write access to whatever filesystem the Unifi Controller was running on (I know some people run it in a cloud based VM for instance).

It would be nice if the unified.sh API exposed some of the functionality that the controller front end application uses to set up firewall rules.

Ultimately I didn't pursue this as my use case was pretty simple and aimed at getting a couple of stubborn teenagers of the internet at night and in to bed :)

**Pull request merged**
